/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Config": {
      "VITE_CLERK_PUBLISHABLE_KEY": string
      "type": "sst.sst.Linkable"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "VPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
