/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignoutImport } from './routes/signout'
import { Route as authedIndexImport } from './routes/(authed)/index'
import { Route as unauthedSignupImport } from './routes/(unauthed)/signup'
import { Route as unauthedSigninImport } from './routes/(unauthed)/signin'
import { Route as authedDashboardIndexImport } from './routes/(authed)/dashboard.index'
import { Route as authedDashboardUsersImport } from './routes/(authed)/dashboard.users'
import { Route as authedDashboardTasksImport } from './routes/(authed)/dashboard.tasks'

// Create/Update Routes

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const authedIndexRoute = authedIndexImport.update({
  id: '/(authed)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const unauthedSignupRoute = unauthedSignupImport.update({
  id: '/(unauthed)/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const unauthedSigninRoute = unauthedSigninImport.update({
  id: '/(unauthed)/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const authedDashboardIndexRoute = authedDashboardIndexImport.update({
  id: '/(authed)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const authedDashboardUsersRoute = authedDashboardUsersImport.update({
  id: '/(authed)/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRoute,
} as any)

const authedDashboardTasksRoute = authedDashboardTasksImport.update({
  id: '/(authed)/dashboard/tasks',
  path: '/dashboard/tasks',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
    '/(unauthed)/signin': {
      id: '/(unauthed)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof unauthedSigninImport
      parentRoute: typeof rootRoute
    }
    '/(unauthed)/signup': {
      id: '/(unauthed)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof unauthedSignupImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/': {
      id: '/(authed)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authedIndexImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/dashboard/tasks': {
      id: '/(authed)/dashboard/tasks'
      path: '/dashboard/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof authedDashboardTasksImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/dashboard/users': {
      id: '/(authed)/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof authedDashboardUsersImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/dashboard/': {
      id: '/(authed)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authedDashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/signout': typeof SignoutRoute
  '/signin': typeof unauthedSigninRoute
  '/signup': typeof unauthedSignupRoute
  '/': typeof authedIndexRoute
  '/dashboard/tasks': typeof authedDashboardTasksRoute
  '/dashboard/users': typeof authedDashboardUsersRoute
  '/dashboard': typeof authedDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/signout': typeof SignoutRoute
  '/signin': typeof unauthedSigninRoute
  '/signup': typeof unauthedSignupRoute
  '/': typeof authedIndexRoute
  '/dashboard/tasks': typeof authedDashboardTasksRoute
  '/dashboard/users': typeof authedDashboardUsersRoute
  '/dashboard': typeof authedDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/signout': typeof SignoutRoute
  '/(unauthed)/signin': typeof unauthedSigninRoute
  '/(unauthed)/signup': typeof unauthedSignupRoute
  '/(authed)/': typeof authedIndexRoute
  '/(authed)/dashboard/tasks': typeof authedDashboardTasksRoute
  '/(authed)/dashboard/users': typeof authedDashboardUsersRoute
  '/(authed)/dashboard/': typeof authedDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signout'
    | '/signin'
    | '/signup'
    | '/'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signout'
    | '/signin'
    | '/signup'
    | '/'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/signout'
    | '/(unauthed)/signin'
    | '/(unauthed)/signup'
    | '/(authed)/'
    | '/(authed)/dashboard/tasks'
    | '/(authed)/dashboard/users'
    | '/(authed)/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SignoutRoute: typeof SignoutRoute
  unauthedSigninRoute: typeof unauthedSigninRoute
  unauthedSignupRoute: typeof unauthedSignupRoute
  authedIndexRoute: typeof authedIndexRoute
  authedDashboardTasksRoute: typeof authedDashboardTasksRoute
  authedDashboardUsersRoute: typeof authedDashboardUsersRoute
  authedDashboardIndexRoute: typeof authedDashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SignoutRoute: SignoutRoute,
  unauthedSigninRoute: unauthedSigninRoute,
  unauthedSignupRoute: unauthedSignupRoute,
  authedIndexRoute: authedIndexRoute,
  authedDashboardTasksRoute: authedDashboardTasksRoute,
  authedDashboardUsersRoute: authedDashboardUsersRoute,
  authedDashboardIndexRoute: authedDashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/signout",
        "/(unauthed)/signin",
        "/(unauthed)/signup",
        "/(authed)/",
        "/(authed)/dashboard/tasks",
        "/(authed)/dashboard/users",
        "/(authed)/dashboard/"
      ]
    },
    "/signout": {
      "filePath": "signout.tsx"
    },
    "/(unauthed)/signin": {
      "filePath": "(unauthed)/signin.tsx"
    },
    "/(unauthed)/signup": {
      "filePath": "(unauthed)/signup.tsx"
    },
    "/(authed)/": {
      "filePath": "(authed)/index.tsx"
    },
    "/(authed)/dashboard/tasks": {
      "filePath": "(authed)/dashboard.tasks.tsx"
    },
    "/(authed)/dashboard/users": {
      "filePath": "(authed)/dashboard.users.tsx"
    },
    "/(authed)/dashboard/": {
      "filePath": "(authed)/dashboard.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
