/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignoutImport } from './routes/signout'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AuthAuthImport } from './routes/auth/_auth'
import { Route as authedDashboardIndexImport } from './routes/(authed)/dashboard.index'
import { Route as authedDashboardUsersImport } from './routes/(authed)/dashboard.users'
import { Route as authedDashboardTasksImport } from './routes/(authed)/dashboard.tasks'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)

const authedDashboardIndexRoute = authedDashboardIndexImport.update({
  id: '/(authed)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const authedDashboardUsersRoute = authedDashboardUsersImport.update({
  id: '/(authed)/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRoute,
} as any)

const authedDashboardTasksRoute = authedDashboardTasksImport.update({
  id: '/(authed)/dashboard/tasks',
  path: '/dashboard/tasks',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/(authed)/dashboard/tasks': {
      id: '/(authed)/dashboard/tasks'
      path: '/dashboard/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof authedDashboardTasksImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/dashboard/users': {
      id: '/(authed)/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof authedDashboardUsersImport
      parentRoute: typeof rootRoute
    }
    '/(authed)/dashboard/': {
      id: '/(authed)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authedDashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthedRoute
  '/signout': typeof SignoutRoute
  '/auth': typeof AuthAuthRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/tasks': typeof authedDashboardTasksRoute
  '/dashboard/users': typeof authedDashboardUsersRoute
  '/dashboard': typeof authedDashboardIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthedRoute
  '/signout': typeof SignoutRoute
  '/auth': typeof AuthAuthRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/tasks': typeof authedDashboardTasksRoute
  '/dashboard/users': typeof authedDashboardUsersRoute
  '/dashboard': typeof authedDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRoute
  '/signout': typeof SignoutRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth': typeof AuthAuthRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(authed)/dashboard/tasks': typeof authedDashboardTasksRoute
  '/(authed)/dashboard/users': typeof authedDashboardUsersRoute
  '/(authed)/dashboard/': typeof authedDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/signout'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/signout'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/_authed'
    | '/signout'
    | '/auth'
    | '/auth/_auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/(authed)/dashboard/tasks'
    | '/(authed)/dashboard/users'
    | '/(authed)/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRoute
  SignoutRoute: typeof SignoutRoute
  AuthRoute: typeof AuthRouteWithChildren
  authedDashboardTasksRoute: typeof authedDashboardTasksRoute
  authedDashboardUsersRoute: typeof authedDashboardUsersRoute
  authedDashboardIndexRoute: typeof authedDashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRoute,
  SignoutRoute: SignoutRoute,
  AuthRoute: AuthRouteWithChildren,
  authedDashboardTasksRoute: authedDashboardTasksRoute,
  authedDashboardUsersRoute: authedDashboardUsersRoute,
  authedDashboardIndexRoute: authedDashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/signout",
        "/auth",
        "/(authed)/dashboard/tasks",
        "/(authed)/dashboard/users",
        "/(authed)/dashboard/"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth",
        "/auth/signin",
        "/auth/signup"
      ]
    },
    "/auth/_auth": {
      "filePath": "auth/_auth.tsx",
      "parent": "/auth"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/(authed)/dashboard/tasks": {
      "filePath": "(authed)/dashboard.tasks.tsx"
    },
    "/(authed)/dashboard/users": {
      "filePath": "(authed)/dashboard.users.tsx"
    },
    "/(authed)/dashboard/": {
      "filePath": "(authed)/dashboard.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
